// SPIKE — NOT PRODUCTION CODE. See docs/ios/swiftui-lifecycle-spike.md.
//
// Route 1 ("reparent") of the SwiftUI-shell spike: tao keeps the application
// lifecycle and creates the whole UIKit hierarchy exactly as it does today.
// After startup, Rust (src-tauri/src/ios_shell.rs) calls into this class,
// which installs a real SwiftUI shell as the window's rootViewController and
// moves wry's existing WKWebView into a container inside that hierarchy.
//
// This file lives in `src-tauri/ios/` because `src-tauri/gen/` is gitignored
// and regenerated by `tauri ios init`. To build it, copy it into
// `src-tauri/gen/apple/Sources/resume-designer/` and run `xcodegen generate`
// inside `src-tauri/gen/apple` — project.yml already globs `Sources`.

import SwiftUI
import UIKit

/// Objective-C entry point Rust calls through `objc_msgSend`. The explicit
/// `@objc(...)` names are load-bearing: Swift would otherwise mangle both the
/// class name and the selector, and `AnyClass::get(c"OPSpikeShell")` would miss.
@objc(OPSpikeShell)
final class OPSpikeShell: NSObject {
  /// Installs the SwiftUI shell into `window` and reparents `webView` into it.
  ///
  /// Must run on the main thread. Rust guarantees single invocation.
  @objc(installShellInWindow:webView:)
  static func installShell(window: UIWindow, webView: UIView) {
    let host = UIHostingController(rootView: SpikeShellView(webView: webView))
    window.rootViewController = host
    window.makeKeyAndVisible()
    NSLog("[OPSpikeShell] installed: root=\(type(of: host)) webview=\(type(of: webView))")
  }
}

/// Wraps the *existing* wry WKWebView — this does not create a new one, which
/// is the whole point: Tauri's IPC, its script message handlers and the loaded
/// document all survive the move.
private struct WebViewHost: UIViewRepresentable {
  let webView: UIView

  func makeUIView(context: Context) -> UIView {
    let container = UIView()
    container.backgroundColor = .systemBackground
    webView.removeFromSuperview()
    // ios_view.rs drives this view by frame + autoresizing mask; inside SwiftUI
    // it is Auto Layout's job instead, so the translation has to be turned off.
    webView.translatesAutoresizingMaskIntoConstraints = false
    container.addSubview(webView)
    NSLayoutConstraint.activate([
      webView.leadingAnchor.constraint(equalTo: container.leadingAnchor),
      webView.trailingAnchor.constraint(equalTo: container.trailingAnchor),
      webView.topAnchor.constraint(equalTo: container.topAnchor),
      webView.bottomAnchor.constraint(equalTo: container.bottomAnchor),
    ])
    return container
  }

  func updateUIView(_ uiView: UIView, context: Context) {}
}

private struct SpikeShellView: View {
  let webView: UIView
  @State private var showSheet = false

  var body: some View {
    NavigationStack {
      WebViewHost(webView: webView)
        .ignoresSafeArea(.container, edges: .bottom)
        .navigationTitle("On Paper")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
          ToolbarItem(placement: .topBarLeading) {
            Button {
              showSheet = true
            } label: {
              Image(systemName: "list.bullet.indent")
            }
          }
          ToolbarItem(placement: .topBarTrailing) {
            Button("Structure") { showSheet = true }
          }
        }
        .sheet(isPresented: $showSheet) {
          SpikeSheet()
        }
    }
  }
}

/// Proves the third thing the spike is asked about: a real
/// `UISheetPresentationController` with detents, which only exists when a
/// genuine UIKit presentation chain owns the screen.
private struct SpikeSheet: View {
  var body: some View {
    NavigationStack {
      List {
        Section("Spike proof") {
          Label("Real sheet, real detents", systemImage: "rectangle.portrait.bottomhalf.filled")
          Label("Drag between medium and large", systemImage: "arrow.up.and.down")
        }
        Section("Below this sheet") {
          Label("wry's WKWebView, still live", systemImage: "safari")
        }
      }
      .navigationTitle("Structure")
      .navigationBarTitleDisplayMode(.inline)
    }
    .presentationDetents([.medium, .large])
    .presentationDragIndicator(.visible)
  }
}
